<div class="news">
                        <div class="newsImageContainer">
                            <a href="http://academy.telerik.com/?utm_source=site&utm_medium=banner&utm_content=300x250&utm_campaign=community" title="Уроци по програмиране"><img width="300" height="250" src="http://academy.telerik.com/images/default-album/telerik-academy-banner-300x250.jpg?sfvrsn=2" alt="Telerik Academy" /></a>
                        </div>
                        <h2>Welcome To <a href="http://academy.telerik.com/">Telerik Academy</a> !</h2>
                        <h3>Become a ninja</h3>
                        <p>&emsp; What is the best way to do something fun and to get paid for it ? Of course to become a programmer. From many years lots of young and not so young people dream to write code and earn the permission to call themselves software developers. I ask myself why it is such a popular profession and there is still a hunger for new talents. Why it is modern and attractive to be a codewriter ? </p>
                        <p>&emsp; The big variety of technologies and the opportunities for big development in the IT sector are very tempting for the people with at least basic mathematical skills and strong motivation for learning new things. Another reason is the fact that this area is least dependent from politics and financial crises(even then there is profit !). That keeps the interest for programming big during all these years and will keep for a long time in the future.</p>
                        <p>&emsp; So here comes the question where is the best place to learn to code if you are in Bulgaria. Of course there are the universities like "Sofia University", "Technical University" and the fresh-opened "Software University". But all these universities want not so little fees to be paid and mostly you will learn just the basics of the IT technologies. So if you want to be really good you have to go deeper in the sphere and <a href="http://academy.telerik.com/">Telerik Academy</a> is the best bonus for your career development.</p>
                        <p>&emsp; Why <a href="http://academy.telerik.com/">Telerik</a> ? First of all it is free. You do not want to pay more money, do you. From my own experience I can say that the whole organization is very professional. They use the latest technologies and keep up with the latest tendencies in the IT sphere. They cover lots of aspects in the area and give you the chance to become a professional developer in the mobile, web or QA sectors. All courses are strong practicaly directed. And, after all, you need to show quality, talent and knowledge, if you want to get a certificate. </p>
                        <p>&emsp; So do not hesitate and become a part of <a href="http://academy.telerik.com/">Telerik Academy</a> !</p>
                    </div>